### Author: Frish2021 ###
name: deploy_pages

on:
  push:
    branches: [ "master" ]
    paths:
      - "../../nbt-docs/**/*"
      - '.github/workflows/deploy_pages.yml'

permissions: write-all

jobs:
  build:
    name: Deploy NBT Docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install --frozen-lockfile
      working-directory: ./nbt-docs

    - name: Build project
      run: pnpm build
      working-directory: ./nbt-docs

    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./nbt-docs/.vitepress/dist
        force_orphan: true
